### ISSUE TITLE
Different programmer.bin per-earbud?

### ISSUE THREAD

**Issue by frap129** [Ralim/BES-programming-tool#3]
The other day, I tried reading the flash off of my pinebuds using this tool and it worked fine on the right earbud, but for the left earbud it would hang while reading the third chunk, somewhere between 10% and 15% (varied between tries). Today I saw the windows tool released on the pinebuds wiki, downloaded it, and replaced `programmer.bin` in this repo with `programmer2300p.bin` out of the windows tool. Based on the `productline_cfg.xml` file in the windows tool, this is the correct programmer for the chip in the pinebuds. I ran this tool again and it was able to read the flash off of the left earbud on the first try! I tried reading the right earbud again now that I had the official programmer aaaaannndd it got stuck at 12% on the third chunk. I tried again, and it got stuck at 15% on the third chunk.

This doesn't really make sense to me, but I thought it may be useful to report.

**Comment by Ralim** [comment]
Hia so this is actually why I haven't pushed this out fully.
The issue is that the programmer.bin does not reset the watchdog. And the PineBuds firmware has it turned on.

So if you get lucky and your read lines up nicely it will work but sometimes it hangs because chip is reset on us.

I have some thoughts on how to get around this but so far they all have a crap UX

**Comment by frap129** [comment]
The reset issue makes sense, and after more testing on my end that appears to be the case. After a 4 more tries using the programmer.bin from the windows tool, it successfully read the right earbud, though I still haven't been able to read the left earbud with the programmer.bin from this repo. I still think its odd that this behavior difference between the two files is somewhat consistent, though it  seems to be only a coincidence.

**Comment by Ralim** [comment]
Yeah its a bit of a mess.
I have (last night) updated to the newer programmer bin; so may be worth a new poke to see if thats better or worse.
